### ISSUE TITLE
Allow Secure SIP Over WebSockets

### ISSUE THREAD

**Issue by deruelle** [Mobicents/olympus#10]
Currently Olympus allow only ws:// as a transport protocol, it should allow wss:// to guarantee secure communications. Critical to run it as a service, especially as Google will not allow non secure URLs to access webcam and microphone anymore soon.

**Comment by deruelle** [comment]
located in olympus.war/resources/js/controllers/register.js

**Comment by deruelle** [comment]
Duplicate of #13

**Comment by KietnaQuTak** [comment]
Hello. I have just stumbled upon "WSMessageChannel:createWebSocket(): websocket connection has failed:[object Event]" error after updating to stable version of Google Chrome (same in v48 beta) and as far as I understand it's a new standard that Google is pushing this update permanently.

You have written "now need the UI to be able to define it as well". I'm using Olympus downloaded 2-3 weeks ago, does it have mention updates? Should I change anything in code to force wss permanently or should it run by default?

Best regards
Kietna Qu'Tak
